name: Main workflow

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    env:
      Prerelease: ci

    steps:
    - name: Print GITHUB_RUN_NUMBER
      run: |
        echo "GITHUB_RUN_NUMBER is ${env:GITHUB_RUN_NUMBER}"
          
    - uses: actions/checkout@v1
      
    - name: Build Projects
      run: |
        dotnet build ./EasyProblems/EasyProblems.csproj -c Release
        dotnet test ./EasyProblems/EasyProblems.csproj
        dotnet build ./MediumProblems/MediumProblems.csproj -c Release
        dotnet test ./MediumProblems/MediumProblems.csproj
        dotnet build ./HardProblems/HardProblems.csproj -c Release
        dotnet test ./HardProblems/HardProblems.csproj
        
