name: Main workflow

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    env:
      Prerelease: ci

    steps:
    - name: Print GITHUB_RUN_NUMBER
      run: |
        echo "GITHUB_RUN_NUMBER is ${env:GITHUB_RUN_NUMBER}"
          
    - uses: actions/checkout@v1
      
    - name: Build Projects
      run: |
        dotnet build ./LeetCode.Examples/EasyProblems.csproj -c Release
        dotnet build ./LeetCode.Examples/MediumProblems.csproj -c Release
        dotnet build ./LeetCode.Examples/HardProblems.csproj -c Release
        
